language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_deploy:
  - cd eslint-config-ringcentral
deploy:
  provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: ringcentral/ringcentral-javascript
